# Generated by Django 4.2.9 on 2025-11-04 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Acción'), ('adventure', 'Aventura'), ('rpg', 'RPG'), ('strategy', 'Estrategia'), ('shooter', 'Shooter'), ('sports', 'Deportes'), ('racing', 'Carreras'), ('fighting', 'Pelea'), ('puzzle', 'Puzzle'), ('simulation', 'Simulación'), ('horror', 'Terror'), ('platform', 'Plataformas'), ('mmorpg', 'MMORPG'), ('moba', 'MOBA'), ('battle_royale', 'Battle Royale')], max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='style',
            field=models.CharField(blank=True, choices=[('2d', '2D'), ('3d', '3D'), ('pixel_art', 'Pixel Art'), ('realistic', 'Realista'), ('cartoon', 'Cartoon'), ('anime', 'Anime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Imagen wallpaper del juego', null=True, upload_to='games/banners/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen para la tarjeta del juego', null=True, upload_to='games/covers/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.JSONField(blank=True, default=list, help_text='Lista de plataformas: PC, PlayStation, Xbox, Switch, Mobile'),
        ),
    ]
