# Generated by Django 4.2.9 on 2025-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_created_by_game_genre_game_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Rating promedio de 0-5', max_digits=2),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
