# Generated by Django 4.2.9 on 2025-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_rating_alter_gamerating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='community_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Rating promedio de la comunidad (0-5)', max_digits=2),
        ),
        migrations.AddField(
            model_name='game',
            name='professional_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Valoración de profesionales GOAT (0-10)', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='professional_review',
            field=models.TextField(blank=True, help_text='Reseña profesional del equipo'),
        ),
    ]
