# Generated by Django 4.2.9 on 2025-11-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_community_rating_game_professional_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='professional_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='professional_review',
        ),
        migrations.AddField(
            model_name='game',
            name='official_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Valoración oficial GOAT (1-5 estrellas)', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='official_review',
            field=models.TextField(blank=True, help_text='Reseña oficial del equipo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='community_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Rating promedio de la comunidad (1-5)', max_digits=2),
        ),
    ]
