# Generated by Django 4.2.9 on 2025-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_professional_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='official_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Valoración oficial GOAT (0-10)', max_digits=3, null=True),
        ),
    ]
