# Generated by Django 4.2.9 on 2025-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_comment_dislikes_comment_game_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Las guías se publican automáticamente'),
        ),
    ]
