# Generated by Django

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    """Populate initial forums and groups"""
    Forum = apps.get_model('community', 'Forum')
    
    # Create Forums only if they don't exist
    forums_data = [
        {
            'name': 'General',
            'slug': 'general',
            'description': 'Charla general sobre videojuegos y gaming',
            'icon': '💬',
            'category': 'general',
            'order': 1
        },
        {
            'name': 'Noticias de Gaming',
            'slug': 'noticias-gaming',
            'description': 'Últimas noticias y novedades del mundo gaming',
            'icon': '📰',
            'category': 'news',
            'order': 2
        },
        {
            'name': 'Guías y Tutoriales',
            'slug': 'guias-tutoriales',
            'description': 'Comparte y encuentra guías para tus juegos favoritos',
            'icon': '📚',
            'category': 'guides',
            'order': 3
        },
        {
            'name': 'Ayuda y Soporte',
            'slug': 'ayuda-soporte',
            'description': '¿Necesitas ayuda? Pregunta aquí',
            'icon': '🆘',
            'category': 'support',
            'order': 4
        },
        {
            'name': 'Discusión de Juegos',
            'slug': 'discusion-juegos',
            'description': 'Debate sobre tus juegos favoritos',
            'icon': '🎮',
            'category': 'games',
            'order': 5
        },
        {
            'name': 'Off Topic',
            'slug': 'off-topic',
            'description': 'Cualquier cosa que no tenga que ver con gaming',
            'icon': '🗨️',
            'category': 'off_topic',
            'order': 6
        },
    ]
    
    for forum_data in forums_data:
        Forum.objects.get_or_create(
            slug=forum_data['slug'],
            defaults=forum_data
        )


def reverse_populate(apps, schema_editor):
    """Remove initial data if migration is reversed"""
    Forum = apps.get_model('community', 'Forum')
    # Don't delete forums on reverse as they might have user content
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_groupjoinrequest'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_populate),
    ]
