# Generated by Django 4.2.9 on 2025-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('goat', 'GOAT')], default='user', max_length=10),
        ),
    ]
