# Generated by Django 4.2.9 on 2025-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('goat', 'GOAT'), ('admin', 'Administrador')], default='user', max_length=10),
        ),
    ]
