# Generated by Django 4.2.9 on 2025-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_guide_is_published'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_guides',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='content.guide'),
        ),
    ]
