# Generated by Django 4.2.9 on 2025-11-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_reply', 'Respuesta a comentario'), ('guide_like', 'Me gusta en guía'), ('guide_rating', 'Valoración en guía'), ('achievement', 'Logro desbloqueado'), ('new_guide_favorite_game', 'Nueva guía de juego favorito'), ('new_follower', 'Nuevo seguidor'), ('system', 'Notificación del sistema'), ('post_reply', 'Respuesta en foro'), ('group_post_comment', 'Comentario en grupo'), ('join_request', 'Solicitud para unirse al grupo'), ('join_approved', 'Solicitud aprobada'), ('join_rejected', 'Solicitud rechazada'), ('group_post', 'Nueva publicación en grupo')], max_length=30),
        ),
    ]
